const COLORS = {
  LIGHT_GREEN: '#45ADA8',
  DARK_GREEN: '#378B87',
  DARK_BLUE: '#9ED0AD',
  DARK_BROWN: '#594F4F',
  GRAY: '#E3E8F0',
  LIGHT_GRAY: '#F7F9FA',
  DARK_GRAY: '#A1A6BB',
}

export default COLORS
